### ISSUE TITLE
target dependencies in module.json

### ISSUE THREAD

**Issue by jrobeson** [ARMmbed/ble-nrf51822#50]
Shoudn't it depend on nrf51822 targets like nordic-nrf51822-16k-gcc ?

**Comment by jrobeson** [comment]
as an aside, do you happen to know where the source code for those nordic targets are hosted? There are some issues in the module.json I'd like to fix. and maybe try to fix up the softdevice logic for s110

**Comment by rgrover** [comment]
ble-nrf51822 does get pulled in as a target dependency when using Nordic targets. Nordic targets for mbed OS are still private because we're blocked on Nordic's approval to ship their softdevice and SDK sources as a part of mbed OS. These targets and modules have been ready to be shipped for more than 6 weeks now; but the process is stuck in legal.

**Comment by jrobeson** [comment]
aha! thanks for the info

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSFW-849

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSFW-1025

**Comment by jrobeson** [comment]
looks like this is really close to being completed now! I was able to set a nordic target to get the mbed-drivers and everything. Thanks to everybody at ARM for making this happen.

**Comment by rgrover** [comment]
it seems this is not an issue anymore. Please reopen if necessary.
